site_name: NMAP
site_url: ""
use_directory_urls: false

theme: 
  name: material
  features:
    - navigation.top
    - navigation.tabs
    - content.code.annotate
    - content.code.copy
    - content.code.select

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - glightbox

nav:
  - Home:
    - Quick Reference: index.md
    - Staying Organized: staying-organized.md
    - Common Tools: common-tools.md
  - NMAP:
    - Intro to NMAP: NMAP/intro-to-nmap.md
    - Host Discovery: NMAP/host-discovery.md
    - Host and Port Scanning: NMAP/host-and-port-scanning.md
    - Saving the Results: NMAP/saving-the-results.md
    - Service Enumeration: NMAP/service-enumeration.md
    - Nmap Scripting Engine: NMAP/nmap-scripting-engine.md
    - Cheat Sheet: NMAP/cheat-sheet.md
    - Targets: 
      - Target: NMAP/target.md
  - Second Tab:
    - Quality of Life Settings: second-tab/guide-qol.md
    - Setting Security: second-tab/guide-security.md
    - Interfaces: second-tab/guide-interfaces.md

